/* Database schema to keep the structure of entire database. */

CREATE TABLE animals (
    id INT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name varchar(100),
    date_of_birth date,
    escape_attempts int,
    neutered boolean,
    weight_kg decimal,
);

/* Add a new column species of type string to the animals table. */

/* ALTER TABLE animals ADD species varchar(100);  */

/* Add column sapecies_id which is a foreign key referencing the id column of the species table. */

ALTER TABLE animals ADD species_id int REFERENCES species(id);

/* Add a new column owner_id which is a foreign key referencing the id column of the owners table. */

ALTER TABLE animals ADD owner_id int REFERENCES owners(id);

/* Create a table named owners with the following columns: */

CREATE TABLE owners (
    id INT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    full_name varchar(100),
    age int,
);

/* Create a table named species with the following columns: */

CREATE TABLE species (
    id INT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name varchar(100),
);
