/* Database schema to keep the structure of entire database. */

CREATE TABLE animals (
    id INT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name varchar(100),
    date_of_birth date,
    escape_attempts int,
    neutered boolean,
    weight_kg decimal,
);

/* Add a new column species of type string to the animals table. */

ALTER TABLE animals ADD species varchar(100);
